package oop2;
 
public class Ex4 {
  public void calc(int tot, int cnt) {
    int avg = tot / cnt;
    
    System.out.println("avg: " + avg);
  }
  
  
  //현재 메소드에서 예외를 처리하지 않고,
  //예외 발생시 호출한 쪽으로 전달
  public void calc2(int tot, int cnt) throws Exception {
    int avg = tot / cnt;
    
    System.out.println("avg: " + avg);
  }
}